const skaurunEntry={title:'Skau’Run: The Bequeathed Weapons of the Spheres',category:'Artifacts',excerpt:'The Grade 9 soul-bound weapons through which Lancers and Emissaries give divine role, Will and authority a physical form.',tags:['Skau’Run','Grade 9','Spherebound','Will Encoding'],status:'Canon',updated:'Today',route:'skaurun'};
const resonanceNullityEntry={title:'Resonance Nullity',category:'Power Systems',excerpt:'The Veil anomaly that makes Marked Ones spiritually silent to the Spheres—and the Auric Choir trained to hunt the unheard.',tags:['Marked Ones','Resonance Nullity','Auric Choir','Ena'],status:'Canon',updated:'Today',route:'resonance-nullity'};
const legendaryTechniquesEntry={title:'Legendary Techniques of Adamantites and Spherebound',category:'Power Systems',excerpt:'Thirty-one named feats through which Adamantites defy the system, Spherebound embody it and Blighted Lancers break it.',tags:['Legendary Techniques','Adamantites','Lancers','RULE'],status:'Canon',updated:'Today',route:'legendary-techniques'};
const racialArtsEntry={title:'Racial Signature Arts of Aulon',category:'Peoples',excerpt:'Thirty-six inherited, cultural and resonant techniques revealing how every Atonis lineage expresses its soul through power.',tags:['Racial Arts','Atonis','Resonance','Techniques'],status:'Canon',updated:'Today',route:'racial-arts'};
const spellsEntry={title:'Named Spells of the Arcane System',category:'Magic',excerpt:'A sixty-spell grimoire of Aulon’s remembered arts, catalogued from the First Walls to Sacred and Moonless threshold magic.',tags:['Named Spells','Grimoire','Arcane Tiers','Spellcraft'],status:'Canon',updated:'Today',route:'spells'};
const arcaneEntry={title:'The Arcane System of Aulon',category:'Magic',excerpt:'The seven-tier system of luminous Arcane Law: color schools, lunar seasons, Phrontisteries, magi ranks and primordial authority.',tags:['Arcane Law','Seven Tiers','Magic Schools','Phrontisteries'],status:'Canon',updated:'Today',route:'arcane'};
const markedEntry={title:'The High Words of Ena and the Sigils of the Marked Ones',category:'Magic',excerpt:'The High Forbidden Words, Moonless Magic and Palinoian brands that sever mortals from the Symphony and begin Blighted transformation.',tags:['Forbidden Lexicon','Marked Ones','Sigils','Moonless Magic'],status:'Canon',updated:'Today',route:'marked'};
const ekharaEntry={title:'Ekhara: The First Tongue of Aulon',category:'Magic',excerpt:'The sacred language translated from divine Hymns, where every word bears a Sphere’s ancestry and Will gives sound consequence.',tags:['Ekhara','Hymns','True Names','Forbidden Lexicon'],status:'Canon',updated:'Today',route:'ekhara'};
const racesEntry={title:'The Races of Aulon',category:'Peoples',excerpt:'The Atonis taxonomy of first people, mortal lineages, elementals, angels, daemons, giants and ascended souls.',tags:['Atonis','Races','Peoples','Soul Resonance'],status:'Canon',updated:'Today',route:'races'};
const artifactsEntry={title:'The Artifact Grading System of Aulon',category:'Artifacts',excerpt:'The ∅–X relic scale governing rarity, potency, divine resonance and the limits of what may be possessed.',tags:['Artifact Grades','Relics','Primordial Items','Hymns'],status:'Canon',updated:'Today',route:'artifacts'};
const lawsEntry={title:'The Twelve Cosmic Laws of Aulon',category:'Cosmology',excerpt:'The foundational Laws of Resonance governing creation, Spheres, souls, ascension, balance, the Veil and revelation.',tags:['Cosmic Laws','Resonance','Aton','The Veil'],status:'Canon',updated:'Today',route:'laws'};
const ruleEntry={title:'RULE and the Lance Phenomenon',category:'Power Systems',excerpt:'The supreme Lancer art: a Grade 9 Lance, Will Encoding and a temporary divine law imposed upon reality.',tags:['RULE','Lance','Will Encoding','Grade 9'],status:'Canon',updated:'Today',route:'rule'};
const sphereboundEntry={title:'Lancers, Emissaries, and Blighted Lancers',category:'Power Systems',excerpt:'The divine, diplomatic and corrupted hierarchies born from direct contact with Sphere Resonance.',tags:['Lancers','Emissaries','Blighted Lancers','RULE'],status:'Canon',updated:'Today',route:'spherebound'};
const adamantiteEntry={title:'The Twelve Adamantites of History',category:'Power Systems',excerpt:'The twelve mortals whose legendary feats reached the edge of divinity without a tether to the Spheres.',tags:['Adamantite','Mortal Legends','Historical Record','Lancers'],status:'Canon',updated:'Today',route:'adamantites'};
const entries=[{title:'Adventurer Guild Ranking System',category:'Power Systems',excerpt:'The nine-rank mortal ladder from Iron to Adamantite, governed by the tenfold power rule.',tags:['Metal Ranks','Combat Power','Adamantite','Lancers'],status:'Canon',updated:'Today',route:'guild'},{title:'Aulla',category:'Spheres',excerpt:'Ephim of Life and Light, whose first song shaped Aulon and kindled the seven lunar dragons.',tags:['Ephim','Creation','Harp'],status:'Canon',updated:'Today'},{title:'Ena',category:'Spheres',excerpt:'The discordant Sphere beyond the Veil; source of the Atrasyll and the Blighted covenants.',tags:['Ephim','Discord','Organistrum'],status:'Canon',updated:'Today'},{title:'The Lancers',category:'Orders',excerpt:'Sphere-tethered champions ranked from Initiate to the singular Primarch, preserving Aulon at any cost.',tags:['Power','Hierarchy','RULE'],status:'Canon',updated:'2 days ago'},{title:'Tarn',category:'Places',excerpt:"The Grande family village and Zirion's childhood home, destroyed on the eve of the harvest festival.",tags:['Village','Third Age','Zirion'],status:'Canon',updated:'3 days ago'},{title:'Atonites',category:'Peoples',excerpt:"Purple-skinned inheritors of Aton's legacy, long-lived masters of hymn-firearms and choir culture.",tags:['Atonis Novo','Ekhara','Choirs'],status:'Canon',updated:'5 days ago'},{title:'Arcane Law',category:'Magic',excerpt:"Aeynu's teaching: spell-bearing light descends from the Bright Moon by day and seven moons by night.",tags:['Aeynu','Schools','Tiers'],status:'Draft',updated:'1 week ago'},{title:'Dru Archa',category:'Cosmology',excerpt:'The Moon Council of seven ancient dragons, each ruling a lunar palace and its adjacent plane.',tags:['Dragons','Moons','First Age'],status:'Canon',updated:'1 week ago'},{title:'Skau’Run',category:'Artifacts',excerpt:"A Lancer's bequeathed divine weapon, bound to the soul until dismissed or carried beyond death.",tags:['Schar','Grade 9','Ekhara'],status:'Canon',updated:'2 weeks ago'}];
entries.unshift(adamantiteEntry);
entries.unshift(sphereboundEntry);
entries.unshift(ruleEntry);
entries.unshift(lawsEntry);
entries.unshift(artifactsEntry);
entries.unshift(racesEntry);
entries.unshift(ekharaEntry);
entries.unshift(markedEntry);
entries.unshift(arcaneEntry);
entries.unshift(spellsEntry);
entries.unshift(racialArtsEntry);
entries.unshift(legendaryTechniquesEntry);
entries.unshift(resonanceNullityEntry);
entries.unshift(skaurunEntry);
const sphereRecords=[
{slug:'aton',name:'Aton',classification:'Primordial',epithet:'The Primordial Force of Attraction and Repulsion, The Conductor of the Choir, The Infinite Expanse',domains:['Attraction','Repulsion','The Infinite Expanse'],instrument:'Not yet recorded',glyph:'∞',color:'#766438'},
{slug:'aulla',name:'Aulla',classification:'Ephims',epithet:'the Blessed Sphere of Life and Light',domains:['Life','Light'],instrument:'Harp',glyph:'A',color:'#6e6635'},
{slug:'ena',name:'Ena',classification:'Ephims',epithet:'The Discordant Sphere of Corruption and Blight',domains:['Corruption','Blight'],instrument:'Organistrum',glyph:'E',color:'#4b3048'},
{slug:'exiyu',name:'Exiyu',classification:'Ephims',epithet:'The Mover of Cycles and Father of Time',domains:['Cycles','Time'],instrument:'Bell',glyph:'X',color:'#4a5d62'},
{slug:'yggra',name:'Yggra',classification:'Ephims',epithet:'The Primeval Animus and Mother of Beasts',domains:['Primeval Animus','Beasts'],instrument:'War Drum',glyph:'Y',color:'#674733'},
{slug:'zeants',name:'Zeants',classification:'Ephims',epithet:'The Sphere of Contracts, Trade and Exchanges',domains:['Contracts','Trade','Exchanges'],instrument:'Chime',glyph:'Z',color:'#7b6536'},
{slug:'zayra',name:'Zayra',classification:'Ephims',epithet:'The Sphere of Love, Embrace and Purity',domains:['Love','Embrace','Purity'],instrument:'Nai',glyph:'Z',color:'#704a55'},
{slug:'schar',name:'Schar',classification:'Ephims',epithet:'The Sphere of War, Honor and Sacrifice',domains:['War','Honor','Sacrifice'],instrument:'Carnyx',glyph:'S',color:'#6b3d32'},
{slug:'aeynu',name:'Aeynu',classification:'Ephims',epithet:'The Sphere of Magic and Arcane Laws, The Equaliser',domains:['Magic','Arcane Laws','The Equaliser'],instrument:'Manichord',glyph:'Æ',color:'#3e3b67'},
{slug:'yanukai',name:'Yanukai',classification:'Ephims',epithet:'The Sphere of Knowledge, The Seeker',domains:['Knowledge','The Seeker'],instrument:'Panpipes',glyph:'Y',color:'#3d5665'},
{slug:'aebu',name:'Aebu',classification:'Foudroyants',epithet:'The Sphere of Order and Justice, The Judge',domains:['Order','Justice','The Judge'],instrument:'Not yet recorded',glyph:'A',color:'#485a55'},
{slug:'uraim',name:'Uraim',classification:'Foudroyants',epithet:'The Sphere of Freedom and Potential',domains:['Freedom','Potential'],instrument:'Not yet recorded',glyph:'U',color:'#49666a'},
{slug:'usawl',name:'Usawl',classification:'Foudroyants',epithet:'The Sphere of Pathways and Fate',domains:['Pathways','Fate'],instrument:'Lyre',glyph:'U',color:'#5d4b70'},
{slug:'heres',name:'Heres',classification:'Foudroyants',epithet:'The Sphere of Sand and Survival',domains:['Sand','Survival'],instrument:'Not yet recorded',glyph:'H',color:'#826940'},
{slug:'hecarim',name:'Hecarim',classification:'Foudroyants',epithet:'The Sphere of Forging and Creativity',domains:['Forging','Creativity'],instrument:'Not yet recorded',glyph:'H',color:'#744b37'},
{slug:'hilde',name:'Hilde',classification:'Foudroyants',epithet:'The Sphere of Beauty, Kindness and Compassion',domains:['Beauty','Kindness','Compassion'],instrument:'Not yet recorded',glyph:'H',color:'#665268'},
{slug:'evas',name:'Evas',classification:'Desiderims',epithet:'The Sphere of Nature, Growth and Abundance, The Gardener',domains:['Nature','Growth','Abundance','The Gardener'],instrument:'Not yet recorded',glyph:'E',color:'#3e6548'},
{slug:'omongo',name:'Omongo',classification:'Desiderims',epithet:'The Sphere of Darkness, Death and Travels, The Herald of Souls and the Lost',domains:['Darkness','Death','Travels','Souls','The Lost'],instrument:'Not yet recorded',glyph:'O',color:'#303747'},
{slug:'grau',name:'Grau',classification:'Desiderims',epithet:'The Sphere of Gravity, Space and Nullity',domains:['Gravity','Space','Nullity'],instrument:'Not yet recorded',glyph:'G',color:'#303e52'},
{slug:'xhin',name:'Xhin',classification:'Dolorifs',epithet:'The Sphere of Lightning and Thunder',domains:['Lightning','Thunder'],instrument:'Not yet recorded',glyph:'X',color:'#4b526e'},
{slug:'ysyllyn',name:'Ysyllyn',classification:'Dolorifs',epithet:'The Sphere of Ice and Snow',domains:['Ice','Snow'],instrument:'Not yet recorded',glyph:'Y',color:'#526d78'},
{slug:'kyntus',name:'Kyntus',classification:'Dolorifs',epithet:'The Sphere of Fire and Warmth',domains:['Fire','Warmth'],instrument:'Not yet recorded',glyph:'K',color:'#7a4734'},
{slug:'traeyla',name:'Traeyla',classification:'Dolorifs',epithet:'The Sphere of Water and Mist',domains:['Water','Mist'],instrument:'Not yet recorded',glyph:'T',color:'#3e6471'},
{slug:'engkalos',name:'Engkalos',classification:'Dolorifs',epithet:'The Sphere of Earth and Stone',domains:['Earth','Stone'],instrument:'Not yet recorded',glyph:'E',color:'#675943'},
{slug:'freiharnt',name:'Freiharnt',classification:'Dolorifs',epithet:'The Sphere of Air and Wind.',domains:['Air','Wind'],instrument:'Not yet recorded',glyph:'F',color:'#526966'},
{slug:'baro-es',name:'Baro-Es',classification:'Palinoians',epithet:'The Sphere of Chaos and Destruction, Embodiment of Wrath',domains:['Chaos','Destruction','Wrath'],instrument:'Not yet recorded',glyph:'B',color:'#683630'},
{slug:'dhiya-ulhak',name:'Dhiya-Ulhak',classification:'Palinoians',epithet:'The Sphere of Plague and Decay, Embodiment of The Sloth',domains:['Plague','Decay','Sloth'],instrument:'Not yet recorded',glyph:'D',color:'#4a5137'},
{slug:'varok-tu',name:'Varok-Tu',classification:'Palinoians',epithet:'The Sphere of Illusion and Trickery, Embodiment of The Envy',domains:['Illusion','Trickery','Envy'],instrument:'Not yet recorded',glyph:'V',color:'#434f3d'},
{slug:'jeskar-ira',name:'Jeskar-Ira',classification:'Palinoians',epithet:'The Sphere of Indulgence and Seduction, Embodiment of Lust',domains:['Indulgence','Seduction','Lust'],instrument:'Not yet recorded',glyph:'J',color:'#713f56'},
{slug:'nith-rhu',name:'Nith-Rhu',classification:'Palinoians',epithet:'The Sphere of Contempt and Gain, Embodiment of Greed',domains:['Contempt','Gain','Greed'],instrument:'Not yet recorded',glyph:'N',color:'#635433'},
{slug:'atho-rhu',name:"Atho'-Rhu",classification:'Palinoians',epithet:'The Sphere of Fear and Despair, Embodiment of Pride',domains:['Fear','Despair','Pride'],instrument:'Not yet recorded',glyph:'A',color:'#403a50'},
{slug:'enala',name:'Enala',classification:'Palinoians',epithet:'The Sphere of Hunger and Famine, Embodiment of Gluttony',domains:['Hunger','Famine','Gluttony'],instrument:'Not yet recorded',glyph:'E',color:'#584038'}
];
